server:
  port: 5000
  routes:
    status: '/status'
    model: '/llm'

models:
  leolm:
    name: "LeoLM/leo-mistral-hessianai-7b-chat"
    split_string_for_answer: "<|im_start|>assistant"
  llama2:
      name: "meta-llama/Llama-2-7b-chat-hf"
      split_string_for_answer: "[/INST]"
