server:
  port: 5000
  routes:
    status: '/status'
    model: '/llm'

models:
  mock:
    name: "offline"
  leolm:
    name: "LeoLM/leo-mistral-hessianai-7b-chat"
  llama2:
      name: "meta-llama/Llama-2-7b-chat-hf"
