version: '3'
services:
  transformers-playground-server:
    build: . 
    image: transformers-playground-server
    container_name: transformers-playground-server
    ports:
      - "5000:5000"  
    volumes:
      - ./resources:/app/resources
      - /var/huggingface:/var/huggingface
    restart: always
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
