version: '3'
services:
  python-server:
    build: . 
    image: python-server
    container_name: python-server
    ports:
      - "5000:5000"  
    volumes:
      - ./resources:/app/resources
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
